
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsuleReleveWS", targetNamespace = "http://wepservice.project2.enset.ma/", wsdlLocation = "http://localhost:9090/?wsdl")
public class ConsuleReleveWS
    extends Service implements ConsulteReleve {

    private final static URL CONSULERELEVEWS_WSDL_LOCATION;
    private final static WebServiceException CONSULERELEVEWS_EXCEPTION;
    private final static QName CONSULERELEVEWS_QNAME = new QName("http://wepservice.project2.enset.ma/", "ConsuleReleveWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULERELEVEWS_WSDL_LOCATION = url;
        CONSULERELEVEWS_EXCEPTION = e;
    }

    public ConsuleReleveWS() {
        super(__getWsdlLocation(), CONSULERELEVEWS_QNAME);
    }

    public ConsuleReleveWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULERELEVEWS_QNAME, features);
    }

    public ConsuleReleveWS(URL wsdlLocation) {
        super(wsdlLocation, CONSULERELEVEWS_QNAME);
    }

    public ConsuleReleveWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULERELEVEWS_QNAME, features);
    }

    public ConsuleReleveWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsuleReleveWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ConsulteReleve
     */
    @WebEndpoint(name = "ConsulteRelevePort")
    public ConsuleReleveWS getConsulteRelevePort() {
        return super.getPort(new QName("http://wepservice.project2.enset.ma/", "ConsulteRelevePort"), ConsulteReleve.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsulteReleve
     */
    @WebEndpoint(name = "ConsulteRelevePort")
    public ConsulteReleve getConsulteRelevePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wepservice.project2.enset.ma/", "ConsulteRelevePort"), ConsulteReleve.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULERELEVEWS_EXCEPTION!= null) {
            throw CONSULERELEVEWS_EXCEPTION;
        }
        return CONSULERELEVEWS_WSDL_LOCATION;
    }

    @Override
    public Releve getReleve(String rib) {
        return null;
    }
}
